# Main config file for [ Alacritty ]


# general.import = ["./rosepine.toml"]

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]

[terminal.shell]
program = "/usr/bin/tmux"

[window]
	decorations = "None"
	opacity = 0.4

[font]
	size = 15
	[font.normal]
			family = "FantasqueSansM Nerd Font Propo"
		style = "SemiBold"

