
# UnBinds
unbind C-b
unbind r
unbind-key -n F1
set -g mouse on





# Binds
bind C-Space send-prefix
bind r source-file ~/.config/tmux/tmux.conf
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R
set-window-option -g mode-keys vi


# Setting modes
set -g mode-style 'fg=black bg=grey'
set -g status-style bg=black,fg=white
set -g pane-border-status top
set -g pane-border-format "─────────────────────────────────────────────────────────"





# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

set-option -g status-position top

# Glob settings
set -g base-index 1          # Start window numbering at 1
set -g pane-base-index 1     # Start pane numbering at 1
set -g renumber-windows on   # Renumber windows when one is closed
set -g default-terminal "screen-256color"  # Better color support
set -g prefix C-Space
set -g status-right-length 200
set -g status-right " [ Fedora ] [ Said ]   %H:%M      "




run '~/.tmux/plugins/tpm/tpm'

